### ISSUE TITLE
Internal server error after column type is converted from text to boolean with display options 

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1228]
## To Reproduce
* Create a new text column
* Patch the column from text to boolean with display options.
  ```javascript
  {
    type: 'boolean',
    type_options: {},
    display_options: {
      input: 'dropdown',
      custom_labels: {
        TRUE: 'TRUE'
        FALSE: 'FALSE'
      }
    }
  }
  ```
* Notice that the request succeeds.
* Send a subsequent request to get all columns of the table. Notice the 500 error.
* Try loading the frontend, a debug page with the error message appears.
* **This does not happen always, happens intermittently and I end up having to drop the table directly in the db inorder to get things working again.**

## Error message:
```
[{"code":4999,"message":"\"Got KeyError when attempting to get a value for field `input` on serializer `BooleanDisplayOptionSerializer`.\\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\\nOriginal exception text was: 'input'.\"","field":null,"detail":null}]
```

## Error log:
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/mathesar_tables/1/?t=W1tdLG51bGxd

Django Version: 3.1.14
Python Version: 3.9.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]

During handling of the above exception ('input'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/mathesar/views.py", line 109, in schema_home
    'common_data': get_common_data(request, database, schema)
  File "/code/mathesar/views.py", line 55, in get_common_data
    'tables': get_table_list(request, schema),
  File "/code/mathesar/views.py", line 35, in get_table_list
    return table_serializer.data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/code/mathesar/api/serializers/columns.py", line 67, in to_representation
    return super().to_representation(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)

Exception Type: KeyError at /mathesar_tables/1/
Exception Value: "Got KeyError when attempting to get a value for field `input` on serializer `BooleanDisplayOptionSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'input'."
```

**Comment by pavish** [comment]
@silentninja @kgodey 

I'm still the same error quite frequently for boolean type. But it's intermittent and I can't seem to reproduce it.

`"Got KeyError when attempting to get a value for field 'input' on serializer 'BooleanDisplayOptionSerializer'.\nThe serializer field might be named incorrectly and not match any attribute or key on the 'dict' instance.\nOriginal exception text was: 'input'."`

Adding a default to `input` in `BooleanDisplayOptionSerializer` seems to fix the issue for me.

[This commit](https://github.com/centerofci/mathesar/pull/1251/commits/1151af59a6775d226448b232ae6d84001110ef75#diff-0cba368aff485c57e63a82055dfe283abac0a640d1896e087ae59d160210270cR106) seems to remove the default. Perhaps we expect the value to always be present but it is missing due to some race condition.

I'm re-opening this issue since it's essentially the same issue and the PRs are related.

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/mathesar_tables/1/?t=W1tbMSwxMSxbWzEsNTAwXSxbXSxbXSxbImFuZCIsW11dXV1dLFsxLDExXV0

Django Version: 3.1.14
Python Version: 3.9.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]

During handling of the above exception ('input'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/mathesar/views.py", line 109, in schema_home
    'common_data': get_common_data(request, database, schema)
  File "/code/mathesar/views.py", line 55, in get_common_data
    'tables': get_table_list(request, schema),
  File "/code/mathesar/views.py", line 35, in get_table_list
    return table_serializer.data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/code/mathesar/api/serializers/columns.py", line 67, in to_representation
    return super().to_representation(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)

Exception Type: KeyError at /mathesar_tables/1/
Exception Value: "Got KeyError when attempting to get a value for field `input` on serializer `BooleanDisplayOptionSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'input'."

```

**Comment by silentninja** [comment]
@pavish I am able to reproduce the bug.

**Comment by silentninja** [comment]
@pavish We had a few Display option bug fixes recently, have you faced this issue in the latest master branch?

**Comment by kgodey** [comment]
I'm closing this, we can reopen if it comes up again.
