### ISSUE TITLE
Query RPC endpoint results in a 500 when summarization when preproc functions are used.

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1692]
## Description
* Using the Query RPC endpoint, run a query with an `initial_column` which contains preproc functions. Eg., `author_website` column which can utilize the preproc function `extract_uri_scheme`.
* Create a summarization transform with a grouping expression utilizing the preproc function.
* Notice that the server throws a 500.

## Example Request
```
{
   "base_table":6,
   "initial_columns":[
      {
         "alias":"author_website",
         "id":34,
         "display_name":"author_website"
      }
   ],
   "transformations":[
      {
         "type":"summarize",
         "spec":{
            "grouping_expressions":[
               {
                  "input_alias":"author_website",
                  "output_alias":"author_website",
                  "preproc":"extract_uri_scheme"
               }
            ],
            "aggregation_expressions":[]
         },
         "display_names":{}
      }
   ],
   "parameters":{
      "limit":100,
      "offset":0
   }
}
```

## Response - 500 from server
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/db/v0/queries/run/

Django Version: 3.1.14
Python Version: 3.9.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 53, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/db/viewsets/queries.py", line 76, in run
    column_metadata = query.all_columns_description_map
  File "/code/mathesar/models/query.py", line 173, in all_columns_description_map
    return {
  File "/code/mathesar/models/query.py", line 174, in <dictcomp>
    alias: self._describe_query_column(sa_col)
  File "/code/mathesar/models/query.py", line 166, in _describe_query_column
    'type': sa_col.db_type.id,
  File "/code/db/columns/base.py", line 211, in db_type
    return get_db_type_enum_from_class(self.type.__class__)
  File "/code/db/types/operations/convert.py", line 37, in get_db_type_enum_from_class
    raise UnknownDbTypeId

Exception Type: UnknownDbTypeId at /api/db/v0/queries/run/
Exception Value: 

```

**Comment by mathemancer** [comment]
Very cool bug, thanks for raising.

The underlying issues are twofold:
1. The SQLAlchemy generic `Text` type is still being erroneously used in some spots in our codebase (easy to fix), and
2. whenever we use a custom or unknown function in SQLAlchemy, we need to add a particular class to the `globals()` dict to let SQLAlchemy know the return type (so it can pass that return type along to the resulting column).

(1) is easy to solve, (2) is tricky. I'm going to solve (2) somewhat temporarily for now, since I don't want to sink too much time into a part of the machine we want to completely overhaul.
