### ISSUE TITLE
AttributeError from columns endpoint

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1791]
I started getting this error from the columns endpoint and I'm not sure how. I would only get the error when requesting the columns for one table. Other tables were fine. But after I started getting this error, I got it consistently until I restarted Docker. After restarting Docker I don't see the error at all anymore.

<details>
<summary>Traceback</summary>

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/api/db/v0/tables/2/columns/?limit=500

Django Version: 3.1.14
Python Version: 3.9.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/code/mathesar/models/base.py", line 675, in __getattribute__
    return super().__getattribute__(name)

During handling of the above exception ('Column' object has no attribute 'valid_target_types'), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 826, in __getattr__
    return getattr(self.comparator, key)

The above exception ('Comparator' object has no attribute 'valid_target_types') was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 55, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/code/mathesar/api/serializers/columns.py", line 84, in to_representation
    representation = super().to_representation(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1882, in to_representation
    return method(value)
  File "/code/mathesar/api/serializers/columns.py", line 204, in get_valid_target_types
    valid_target_types = column.valid_target_types
  File "/code/mathesar/models/base.py", line 681, in __getattribute__
    return getattr(self._sa_column, name)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 828, in __getattr__
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception

Exception Type: AttributeError at /api/db/v0/tables/2/columns/
Exception Value: Neither 'Column' object nor 'Comparator' object has an attribute 'valid_target_types'
```

</details>

CC @mathemancer

**Comment by kgodey** [comment]
This is the same error as https://github.com/centerofci/mathesar/issues/1776

**Comment by pavish** [comment]
I also got this error earlier after #1775 was merged.

**Comment by mathemancer** [comment]
I've been working on other things, hoping I'd bump into this bug so I could reproduce. So far, I haven't.

Unless I randomly do crash into it today, and if we can't come up with a way to reproduce reliably, I'll probably submit a PR that would solve what I _think_ might be wrong. That makes me a bit uncomfortable, but the operation introduced will be pretty cheap, so it shouldn't be too much of a problem to just do it regardless.

**Comment by mathemancer** [comment]
UPDATE:

I've managed to crash into this bug (at last). It appears to be a problem with our custom `cached_property` decorator. I'm conferring with @dmos62 in other channels to see if the value we're getting from being able to control our cache clearing more precisely is worth the cost of increased complexity (and bug potential).

**Comment by dmos62** [comment]
We're still talking about this with @mathemancer async, but I want to defend the mechanism in question, for the benefit of anyone reading this thread, by saying that in my view the custom `cached_property` reduces complexity and bug potential by simplifying our state. As I understand the problem, if the bug is in the decorator, it should be easy to fix; otherwise, our reflection is becoming stale because we're not resetting it somewhere where we should be.

**Comment by silentninja** [comment]
I found a bug that was introduced by my PR #1728. This happens when a stale column does not get deleted properly.

**Comment by mathemancer** [comment]
@seancolsen Have you experienced this since the merge of #1728 ? If not, I think we should close it, and reopen if it reoccurs.

**Comment by seancolsen** [comment]
@mathemancer 

> Have you experienced this since the merge of #1728?

Yes. #1728 was merged on 2022-10-07. Pavish and I have both reported experiencing this error after #1775 was merged, which was on 2022-10-10. That said, I haven't run into this bug for at least a week. I can understand that this ticket lacks sufficient detail to be actionable, so it's fine with me if you'd like to close it. We can re-open it if we're able to provide more detail.

**Comment by mathemancer** [comment]
Ah, so sorry. I meant since #1837 was merged a couple days ago.

**Comment by seancolsen** [comment]
@mathemancer Ok in that case, no, I have not observed this bug since #1837 was merged.

**Comment by kgodey** [comment]
We should close this per discussion in today's weekly meeting. We can reopen if it occurs again.

**Comment by mathemancer** [comment]
Okay, I now think this was reopened incorrectly
