### ISSUE TITLE
AssertionError while creating new record

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1863]
## Description
I got this error while creating a new record. I could not find a reliable method to reproduce this, but once I got this error, I kept getting it consistently until I restarted our service.

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/db/v0/tables/159/records/

Django Version: 3.1.14
Python Version: 3.9.14
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 55, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/db/viewsets/records.py", line 139, in create
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 206, in save
    assert self.instance is not None, (

Exception Type: AssertionError at /api/db/v0/tables/159/records/
Exception Value: `create()` did not return an object instance.
```

cc @mathemancer

**Comment by silentninja** [comment]
@mathemancer I think this seems to be problem with the `_sa_table` metadata not knowing about the primary_key of the inserted record. Can you take a look at the issue, I am not able to reproduce nor find the correct cause of the bug

**Comment by pavish** [comment]
@silentninja 

> There are a few reasons why this error could occur

Neither of the mentioned cases happened.

On the plus side, I've not encountered this issue since the time of reporting this issue. I think it's okay to close this, and we can reopen if anyone encounters it again.

**Comment by mathemancer** [comment]
Okay, closing as suggested (for now).
