### ISSUE TITLE
Auth problem with the records endpoint after session expiry

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2067]
After my session on the staging site expired, I pressed the "Refresh" UI button within the Table Page. 

- The columns and constraints endpoints responded appropriately with an HTTP 403 and the following body:

    ```json
    [
      {
        "code": 4003,
        "message": "Authentication credentials were not provided.",
        "details": { "exception": "Authentication credentials were not provided." }
      }
    ]
    ```

- But the records endpoint gave me an HTTP 500 and the following Django error 

    <details>
    <summary>Traceback</summary>

    ```
    Environment:


    Request Method: GET
    Request URL: https://staging.mathesar.org/api/db/v0/tables/12454/records/?limit=500&offset=0&order_by=%5B%7B%22field%22%3A79900%2C%22direction%22%3A%22asc%22%7D%5D&filter=%7B%22and%22%3A%5B%7B%22equal%22%3A%5B%7B%22column_id%22%3A%5B62229%5D%7D%2C%7B%22literal%22%3A%5B8%5D%7D%5D%7D%2C%7B%22lesser%22%3A%5B%7B%22column_id%22%3A%5B62697%5D%7D%2C%7B%22literal%22%3A%5B%22100%22%5D%7D%5D%7D%5D%7D

    Django Version: 3.1.14
    Python Version: 3.9.2
    Installed Applications:
    ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_property_filter',
    'mathesar']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mathesar.middleware.CursorClosedHandlerMiddleware',
    'mathesar.middleware.PasswordChangeNeededMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django_request_cache.middleware.RequestCacheMiddleware']



    Traceback (most recent call last):
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
        return int(value)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/contrib/auth/models.py", line 414, in __int__
        raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')

    The above exception (Cannot cast AnonymousUser to int. Are you trying to use it in place of User?) was the direct cause of the following exception:
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
        return self.dispatch(request, *args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
        response = self.handle_exception(exc)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
        response = exception_handler(exc, context)
      File "/var/www/staging.mathesar.org/mathesar/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
        raise exc
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 497, in dispatch
        self.initial(request, *args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 415, in initial
        self.check_permissions(request)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 332, in check_permissions
        if not permission.has_permission(request, self):
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/access_policy.py", line 53, in has_permission
        allowed = self._evaluate_statements(statements, request, view, action)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/access_policy.py", line 101, in _evaluate_statements
        matched = self._get_statements_matching_conditions(
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/access_policy.py", line 235, in _get_statements_matching_conditions
        passed = bool(boolExpr.parseString(condition)[0])
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/parsing.py", line 32, in __bool__
        return self.evalop(bool(a) for a in self.args)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/parsing.py", line 32, in <genexpr>
        return self.evalop(bool(a) for a in self.args)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/parsing.py", line 14, in __bool__
        return self.check_condition_fn(self.label)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/access_policy.py", line 218, in <lambda>
        check_cond_fn = lambda cond: self._check_condition(
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/rest_access_policy/access_policy.py", line 263, in _check_condition
        result = method(request, view, action)
      File "/var/www/staging.mathesar.org/mathesar/mathesar/api/db/permissions/records.py", line 37, in is_table_viewer
        is_schema_viewer = SchemaRole.objects.filter(
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
        return self._filter_or_exclude(False, *args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
        clone._filter_or_exclude_inplace(negate, *args, **kwargs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
        self._query.add_q(Q(*args, **kwargs))
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1360, in add_q
        clause, _ = self._add_q(q_object, self.used_aliases)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1379, in _add_q
        child_clause, needed_inner = self.build_filter(
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1321, in build_filter
        condition = self.build_lookup(lookups, col, value)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1167, in build_lookup
        lookup = lookup_class(lhs, rhs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
        self.rhs = self.get_prep_lookup()
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
        self.rhs = target_field.get_prep_value(self.rhs)
      File "/opt/virtualenvs/staging-mathesar/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
        raise e.__class__(

    Exception Type: TypeError at /api/db/v0/tables/12454/records/
    Exception Value: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7fe07d769820>.
    ```
    </details>

CC @mathemancer @kgodey

I'm putting this in the First Release milestone, but only because I think someone from the backend team should look at it and then decide how to better prioritize it.

**Comment by kgodey** [comment]
I put this in the "public launch" milestone, it's not a release blocker since it's just throwing the wrong kind of error.

**Comment by pavish** [comment]
This issue was fixed by https://github.com/centerofci/mathesar/pull/2460
