### ISSUE TITLE
Hide transformation results in a 500 in /run request

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2077]
## Description
Adding a hide transformation results in a 500 with the following error:
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/db/v0/queries/run/

Django Version: 3.1.14
Python Version: 3.9.15
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/db/viewsets/queries.py", line 123, in run
    column_metadata = query.all_columns_description_map
  File "/code/mathesar/models/query.py", line 248, in all_columns_description_map
    return {
  File "/code/mathesar/models/query.py", line 249, in <dictcomp>
    alias: self._describe_query_column(sa_col)
  File "/code/mathesar/models/query.py", line 217, in _describe_query_column
    type=sa_col.db_type.id,
  File "/code/db/columns/base.py", line 225, in db_type
    return get_db_type_enum_from_class(self.type.__class__)
  File "/code/db/types/operations/convert.py", line 37, in get_db_type_enum_from_class
    raise UnknownDbTypeId

Exception Type: UnknownDbTypeId at /api/db/v0/queries/run/
Exception Value: 
```

The request:
```json
{
   "base_table":72,
   "initial_columns":[
      {
         "id":225,
         "alias":"Patrons_First Name"
      },
      {
         "id":226,
         "alias":"Patrons_Last Name"
      },
      {
         "id":227,
         "alias":"Patrons_Email"
      }
   ],
   "transformations":[
      {
         "type":"hide",
         "spec":[]
      }
   ],
```

**Comment by dmos62** [comment]
`hide` transformation is not valid when `spec` is an empty list. At least one input alias is expected to be in the list. Not certain that that's the cause for the 500 though. I'll investigate.

**Comment by pavish** [comment]
@dmos62 The error is thrown even when `spec` contains values. The request was an example.

Additionally, I think it'll be great if the backend _does **not**_ validate the spec to contain atleast one value. It'll save a lot of time on the frontend.

**Comment by dmos62** [comment]
This is fixed in above mentioned PR.
