### ISSUE TITLE
AttributeError error "attname" when renaming a newly created table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2089]
## Steps to reproduce

1. Begin with our Library Schema.
1. From the schema page, choose "New Table" > "From Scratch".
1. When the Table Page loads, rename the table to "Reviews".
1. Observe the following error when loading the records for the table:

    <details>
    <summary>Traceback</summary>

    ```
    Environment:


    Request Method: GET
    Request URL: http://localhost:8000/api/db/v0/tables/129/records/?limit=500&offset=0

    Django Version: 3.1.14
    Python Version: 3.9.16
    Installed Applications:
    ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_property_filter',
    'mathesar']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mathesar.middleware.CursorClosedHandlerMiddleware',
    'mathesar.middleware.PasswordChangeNeededMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django_request_cache.middleware.RequestCacheMiddleware']



    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1167, in __getattr__
        return self._index[key]

    The above exception ('attname') was the direct cause of the following exception:
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
        response = exception_handler(exc, context)
      File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
        raise exc
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
        response = handler(request, *args, **kwargs)
      File "/code/mathesar/api/db/viewsets/records.py", line 55, in list
        column_names_to_ids = table.get_column_name_id_bidirectional_map()
      File "/code/mathesar/models/base.py", line 543, in get_column_name_id_bidirectional_map
        columns_map = bidict({column.name: column.id for column in columns})
      File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 287, in __iter__
        self._fetch_all()
      File "/code/mathesar/utils/prefetch.py", line 158, in _fetch_all
        prefetcher.fetch(obj_list, name, self.model, forwarders)
      File "/code/mathesar/utils/prefetch.py", line 270, in fetch
        related_data = self.filter(data_mapping.keys(), data_mapping.values())
      File "/code/mathesar/models/base.py", line 222, in filter
        return get_map_of_attnum_to_column_name(
      File "/code/db/columns/operations/select.py", line 91, in get_map_of_attnum_to_column_name
        triples_of_col_info = _get_triples_of_column_name_and_attnum_and_table_oid(
      File "/code/db/columns/operations/select.py", line 104, in _get_triples_of_column_name_and_attnum_and_table_oid
        statement = _statement_for_triples_of_column_name_and_attnum_and_table_oid(
      File "/code/db/columns/operations/select.py", line 180, in _statement_for_triples_of_column_name_and_attnum_and_table_oid
        sel = select(pg_attribute.c.attname, pg_attribute.c.attnum, pg_attribute.c.attrelid)
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1169, in __getattr__
        util.raise_(AttributeError(key), replace_context=err)
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
        raise exception

    Exception Type: AttributeError at /api/db/v0/tables/129/records/
    Exception Value: attname

    ```

    </details>

Here's a video which demos the above steps

https://user-images.githubusercontent.com/42411/207400140-bc4fdd90-6655-4213-95ce-a5cb111f6749.mp4

(The screencap continues on past this error, in reproducing another issue which may or may not be related to this one.)

**Comment by seancolsen** [comment]
Duplicated of #2138
