### ISSUE TITLE
SortFieldNotFound error when linking to a newly-created table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2090]
## Steps to reproduce

1. Begin with our Library Schema and the code in my PR #2080.
1. From the schema page, choose "New Table" > "From Scratch".
1. When the Table Page loads, rename the table to "Reviews".
1. Note that we get an error when loading the records. That error is reported in #2089. I'm not sure if it's related to the error I'm reporting now.
1. Create a new "Many to One" link to the Publications table. (Note that since recording the video below, the "Many to One" option has been relocated to the first option.)
1. Attempt to add a new record to "Reviews".
1. Observe the records POST request to fail with the following error

    <details>
    <summary>Traceback</summary>

    ```
    Environment:


    Request Method: POST
    Request URL: http://localhost:8000/api/db/v0/tables/89/records/

    Django Version: 3.1.14
    Python Version: 3.9.16
    Installed Applications:
    ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_property_filter',
    'mathesar']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mathesar.middleware.CursorClosedHandlerMiddleware',
    'mathesar.middleware.PasswordChangeNeededMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django_request_cache.middleware.RequestCacheMiddleware']



    Traceback (most recent call last):
      File "/code/db/columns/utils.py", line 70, in find_column_by_name_in_relation
        return relation.columns[col_name_string]
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1158, in __getitem__
        return self._index[key]

    During handling of the above exception (Column('439__323__col__323', INTEGER(), table=<anon_1>, primary_key=True, nullable=False)), another exception occurred:
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 826, in __getattr__
        return getattr(self.comparator, key)

    The above exception ('Comparator' object has no attribute 'split') was the direct cause of the following exception:
      File "/code/db/columns/utils.py", line 54, in get_column_obj_from_relation
        column = find_column_by_name_in_relation(relation, column)
      File "/code/db/columns/utils.py", line 72, in find_column_by_name_in_relation
        col_name_split = col_name_string.split(sep='.', maxsplit=1)
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 828, in __getattr__
        util.raise_(
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
        raise exception

    During handling of the above exception (Neither 'Column' object nor 'Comparator' object has an attribute 'split'), another exception occurred:
      File "/code/db/records/operations/sort.py", line 57, in _get_sorted_column_obj_from_spec
        column = col_utils.get_column_obj_from_relation(relation, sort_spec.field)
      File "/code/db/columns/utils.py", line 56, in get_column_obj_from_relation
        column = relation.columns[column.name]
      File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1158, in __getitem__
        return self._index[key]

    During handling of the above exception ('439__323__col__323'), another exception occurred:
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
        response = exception_handler(exc, context)
      File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
        raise exc
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
        response = handler(request, *args, **kwargs)
      File "/code/mathesar/api/db/viewsets/records.py", line 155, in create
        records = paginator.paginate_queryset(
      File "/code/mathesar/api/pagination.py", line 89, in paginate_queryset
        records = query.get_records(
      File "/code/mathesar/models/query.py", line 172, in get_records
        return self.db_query.get_records(**kwargs)
      File "/code/db/queries/base.py", line 108, in get_records
        return records_select.get_records_with_default_order(
      File "/code/db/records/operations/select.py", line 28, in get_records_with_default_order
        return get_records(
      File "/code/db/records/operations/select.py", line 70, in get_records
        relation = apply_transformations_deprecated(
      File "/code/db/transforms/operations/apply.py", line 55, in apply_transformations_deprecated
        relation = apply_transformations(relation, transforms)
      File "/code/db/transforms/operations/apply.py", line 8, in apply_transformations
        relation = _apply_transform(relation, transform)
      File "/code/db/transforms/operations/apply.py", line 14, in _apply_transform
        relation = transform.apply_to_relation(relation)
      File "/code/db/transforms/base.py", line 124, in apply_to_relation
        executable = rec_sort.apply_relation_sorting(relation, order_by)
      File "/code/db/records/operations/sort.py", line 44, in apply_relation_sorting
        order_by_list = [
      File "/code/db/records/operations/sort.py", line 45, in <listcomp>
        _get_sorted_column_obj_from_spec(relation, spec) for spec in sort_spec
      File "/code/db/records/operations/sort.py", line 59, in _get_sorted_column_obj_from_spec
        raise SortFieldNotFound(e)

    Exception Type: SortFieldNotFound at /api/db/v0/tables/89/records/
    Exception Value: '439__323__col__323'
    ```

    </details>

https://user-images.githubusercontent.com/42411/207400140-bc4fdd90-6655-4213-95ce-a5cb111f6749.mp4

**Comment by kgodey** [comment]
@seancolsen Please test with newest `master`, `SortFieldNotFound` was the same backend error that was fixed in https://github.com/centerofci/mathesar/pull/2082 which was merged very recently.

**Comment by seancolsen** [comment]
I'm no longer able to reproduce this.
