### ISSUE TITLE
ModuleNotFoundError for module django_request_cache

### ISSUE THREAD

**Issue by IyadElwy** [centerofci/mathesar#2214]
## Description
When the user does a clean clone of mathesar and wants to start the application via `docker-compose up` they are met with a `ModuleNotFoundError ` caused by the `django_request_cache`  module.

## To Reproduce
To reproduce do a clean clone of mathesar and start the application via the instructions in the `README.md`

## Traceback
```csharp
mathesar_service  | Traceback (most recent call last):
mathesar_service  |   File "/code/manage.py", line 22, in <module>
mathesar_service  |     main()
mathesar_service  |   File "/code/manage.py", line 18, in main
mathesar_service  |     execute_from_command_line(sys.argv)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_c
ommand_line
mathesar_service  |     utility.execute()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute       
mathesar_service  |     django.setup()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
mathesar_service  |     apps.populate(settings.INSTALLED_APPS)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
mathesar_service  |     app_config.import_models()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
mathesar_service  |     self.models_module = import_module(models_module_name)
mathesar_service  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
mathesar_service  |     return _bootstrap._gcd_import(name[level:], package, level)
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
mathesar_service  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
mathesar_service  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
mathesar_service  |   File "/code/mathesar/models/__init__.py", line 2, in <module>
mathesar_service  |     from .users import User  # noqa
mathesar_service  |   File "/code/mathesar/models/users.py", line 5, in <module>
mathesar_service  |     from mathesar.models.base import BaseModel, Database, Schema
mathesar_service  |   File "/code/mathesar/models/base.py", line 50, in <module>
mathesar_service  |     from mathesar.utils import models as model_utils
mathesar_service  |   File "/code/mathesar/utils/models.py", line 15, in <module>
mathesar_service  |     from mathesar.state import reset_reflection
mathesar_service  |   File "/code/mathesar/state/__init__.py", line 1, in <module>
mathesar_service  |     from mathesar.state.base import make_sure_initial_reflection_happened, reset_reflection  # noqa: F401      
mathesar_service  |   File "/code/mathesar/state/base.py", line 2, in <module>
mathesar_service  |     from mathesar.state.metadata import reset_cached_metadata, get_cached_metadata
mathesar_service  |   File "/code/mathesar/state/metadata.py", line 2, in <module>
mathesar_service  |     from django_request_cache import cache_for_request
mathesar_service  | ModuleNotFoundError: No module named 'django_request_cache'
mathesar_service  | Traceback (most recent call last):
mathesar_service  |   File "/code/manage.py", line 22, in <module>
mathesar_service  |     main()
mathesar_service  |   File "/code/manage.py", line 18, in main
mathesar_service  |     execute_from_command_line(sys.argv)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_c
ommand_line
mathesar_service  |     utility.execute()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute       
mathesar_service  |     django.setup()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
mathesar_service  |     apps.populate(settings.INSTALLED_APPS)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
mathesar_service  |     app_config.import_models()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
mathesar_service  |     self.models_module = import_module(models_module_name)
mathesar_service  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
mathesar_service  |     return _bootstrap._gcd_import(name[level:], package, level)
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
mathesar_service  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
mathesar_service  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
mathesar_service  |   File "/code/mathesar/models/__init__.py", line 2, in <module>
mathesar_service  |     from .users import User  # noqa
mathesar_service  |   File "/code/mathesar/models/users.py", line 5, in <module>
mathesar_service  |     from mathesar.models.base import BaseModel, Database, Schema
mathesar_service  |   File "/code/mathesar/models/base.py", line 50, in <module>
mathesar_service  |     from mathesar.utils import models as model_utils
mathesar_service  |   File "/code/mathesar/utils/models.py", line 15, in <module>
mathesar_service  |     from mathesar.state import reset_reflection
mathesar_service  |   File "/code/mathesar/state/__init__.py", line 1, in <module>
mathesar_service  |     from mathesar.state.base import make_sure_initial_reflection_happened, reset_reflection  # noqa: F401      
mathesar_service  |   File "/code/mathesar/state/base.py", line 2, in <module>
mathesar_service  |     from mathesar.state.metadata import reset_cached_metadata, get_cached_metadata
mathesar_service  |   File "/code/mathesar/state/metadata.py", line 2, in <module>
mathesar_service  |     from django_request_cache import cache_for_request
mathesar_service  | ModuleNotFoundError: No module named 'django_request_cache'
mathesar_service  | Watching for file changes with StatReloader
mathesar_service  | Exception in thread django-main-thread:
mathesar_service  | Traceback (most recent call last):
mathesar_service  |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
mathesar_service  |     self.run()
mathesar_service  |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
mathesar_service  |     self._target(*self._args, **self._kwargs)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
mathesar_service  |     fn(*args, **kwargs)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inne
r_run
mathesar_service  |     autoreload.raise_last_exception()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception   
mathesar_service  |     raise _exception[1]
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute       
mathesar_service  |     autoreload.check_errors(django.setup)()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
mathesar_service  |     fn(*args, **kwargs)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
mathesar_service  |     apps.populate(settings.INSTALLED_APPS)
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
mathesar_service  |     app_config.import_models()
mathesar_service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
mathesar_service  |     self.models_module = import_module(models_module_name)
mathesar_service  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
mathesar_service  |     return _bootstrap._gcd_import(name[level:], package, level)
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
mathesar_service  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
mathesar_service  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
mathesar_service  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
mathesar_service  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
mathesar_service  |   File "/code/mathesar/models/__init__.py", line 2, in <module>
mathesar_service  |     from .users import User  # noqa
mathesar_service  |   File "/code/mathesar/models/users.py", line 5, in <module>
mathesar_service  |     from mathesar.models.base import BaseModel, Database, Schema
mathesar_service  |   File "/code/mathesar/models/base.py", line 50, in <module>
mathesar_service  |     from mathesar.utils import models as model_utils
mathesar_service  |   File "/code/mathesar/utils/models.py", line 15, in <module>
mathesar_service  |     from mathesar.state import reset_reflection
mathesar_service  |   File "/code/mathesar/state/__init__.py", line 1, in <module>
mathesar_service  |     from mathesar.state.base import make_sure_initial_reflection_happened, reset_reflection  # noqa: F401
mathesar_service  |   File "/code/mathesar/state/base.py", line 2, in <module>
mathesar_service  |     from mathesar.state.metadata import reset_cached_metadata, get_cached_metadata
mathesar_service  |   File "/code/mathesar/state/metadata.py", line 2, in <module>
mathesar_service  |     from django_request_cache import cache_for_request
mathesar_service  | ModuleNotFoundError: No module named 'django_request_cache'


```

**Comment by Anish9901** [comment]
@IyadElwy Running `docker exec mathesar_service pip install -r requirements.txt` after running `docker-compose up` should fix the issue. But this shouldn't be happening with a fresh install. When was the last time you built/rebuilt your container?

**Comment by IyadElwy** [comment]
@Anish9901 You're right, when I rebuilt the container it worked correctly, thanks!
