### ISSUE TITLE
Trying to add/patch a user with a set of roles results in a 500

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2321]
## Description
Trying to add a new user with roles results in a 500.
POST: /users/
```
{
  full_name: 'user123',
  username: 'user123',
  password: 'user123', 
  database_roles: [{ database: 1, role: 'manager' }],
}
```

Error:
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/ui/v0/users/

Django Version: 3.1.14
Python Version: 3.9.16
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/code/mathesar/api/ui/serializers/users.py", line 53, in create
    user = User(**validated_data)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 496, in __init__
    _setattr(self, prop, kwargs[prop])
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 545, in __set__
    raise TypeError(

Exception Type: TypeError at /api/ui/v0/users/
Exception Value: Direct assignment to the reverse side of a related set is prohibited. Use database_roles.set() instead.

```

The frontend needs to be able to create a user and assign roles to the user with a single request because the UX is designed to be that way.

**Comment by pavish** [comment]
This needs to be allowed during `PATCH` as well.

**Comment by pavish** [comment]
We are currently working on updating the UX, which might render this issue void. However, this will remain open until the UX is finalized.

**Comment by kgodey** [comment]
Marking as blocked until the UX is finalized.

**Comment by pavish** [comment]
@kgodey 

The updated UX now modifies permissions to be sent in a separate request from the user details, however, this poses another concern.

The UX still requires the user to post all permissions in a single request. But we have 2 separate APIs database_roles and schema_roles to accept each individually one at a time.

The updated UX requires a single endpoint that can accept both `database_roles` and `schema_roles`. If we're doing this, we might as well update the users endpoint to allow patching them in.

**Comment by aagman945** [comment]
@kgodey I would like to work on this issue

**Comment by pavish** [comment]
@aagman945 This issue is restricted to maintainers and blocked. You can notice the tags to identify the issue status.

Please try to look for an issue which is marked as status: ready and is not restricted.
