### ISSUE TITLE
TypeError from schema_roles API when unauthenticated

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2451]
## Reproduce

1. Make sure you're not logged in

1. Request `/api/ui/v0/database_roles/`

1. Observe the following

    <details>
    <summary>Traceback</summary>

    ```
    Environment:


    Request Method: GET
    Request URL: https://staging.mathesar.org/api/ui/v0/schema_roles/

    Django Version: 3.1.14
    Python Version: 3.9.2
    Installed Applications:
    ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_property_filter',
    'mathesar']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mathesar.middleware.CursorClosedHandlerMiddleware',
    'mathesar.middleware.PasswordChangeNeededMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django_request_cache.middleware.RequestCacheMiddleware']



    Traceback (most recent call last):
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
        return int(value)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/contrib/auth/models.py", line 414, in __int__
        raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')

    The above exception (Cannot cast AnonymousUser to int. Are you trying to use it in place of User?) was the direct cause of the following exception:
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
        response = response.render()
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/template/response.py", line 105, in render
        self.content = self.rendered_content
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
        ret = renderer.render(self.data, accepted_media_type, context)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/rest_framework/renderers.py", line 724, in render
        context = self.get_context(data, accepted_media_type, renderer_context)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/rest_framework/renderers.py", line 702, in get_context
        'filter_form': self.get_filter_form(data, view, request),
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/rest_framework/renderers.py", line 630, in get_filter_form
        queryset = view.get_queryset()
      File "/var/www/staging.mathesar.org/mathesar/mathesar/api/ui/viewsets/users.py", line 75, in get_queryset
        return self.access_policy.scope_queryset(
      File "/var/www/staging.mathesar.org/mathesar/mathesar/api/ui/permissions/schema_role.py", line 30, in scope_queryset
        databases_with_view_access = Database.objects.filter(
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 942, in filter
        return self._filter_or_exclude(False, *args, **kwargs)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
        clone._filter_or_exclude_inplace(negate, *args, **kwargs)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
        self._query.add_q(Q(*args, **kwargs))
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1360, in add_q
        clause, _ = self._add_q(q_object, self.used_aliases)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1379, in _add_q
        child_clause, needed_inner = self.build_filter(
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1239, in build_filter
        return self._add_q(
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1379, in _add_q
        child_clause, needed_inner = self.build_filter(
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1321, in build_filter
        condition = self.build_lookup(lookups, col, value)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1167, in build_lookup
        lookup = lookup_class(lhs, rhs)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/lookups.py", line 24, in __init__
        self.rhs = self.get_prep_lookup()
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/fields/related_lookups.py", line 117, in get_prep_lookup
        self.rhs = target_field.get_prep_value(self.rhs)
      File "/opt/virtualenvs/mathesar/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
        raise e.__class__(

    Exception Type: TypeError at /api/ui/v0/schema_roles/
    Exception Value: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x7fd37113adc0>.
    ```

    </details>

**Comment by IamEzio** [comment]
Hi @seancolsen, I'll be happy to work on this issue.
Could you please clarify the desired behavior? Should the logged out user be redirected to Login page when he tries to access `/api/ui/v0/database_roles/`?

**Comment by pavish** [comment]
This should be covered by https://github.com/centerofci/mathesar/issues/2193. So, marking this as duplicate.

@IamEzio Please feel free to look for another available issue.
