### ISSUE TITLE
Do not include unconfirmed tables for `schema.num_tables` for users with viewer & editor access

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2469]
## Description
Request to `/api/db/v0/schemas/` and `http://localhost:8000/api/db/v0/schemas/<schema_id>` have count for `num_tables` which contains count of all tables including ones that are not confirmed.

Confirmation can currently only be performed by a schema manager or a db manager. Users with viewer and editor access cannot see tables that aren't confirmed yet on the UI. This leads to the count being inconsistent.

## Expected behavior
* For DB manager or Schema manager: `num_tables` should include unconfirmed tables.
* For other roles: `num_tables` should not include unconfirmed tables.

## Suggested approach:
* The backend should provide two properties, instead of one:
  - `num_confirmed_tables`
  - `num_unconfirmed_tables`
* The frontend will use these to show counts as needed.

**Comment by pavish** [comment]
I updated the description since this needs a permission check at the API level and removed frontend tag.

**Comment by pavish** [comment]
@silentninja @Anish9901 I've removed the `good first issue` tag since I'm not sure about the work required. Please add it back if you think it should be simple.

**Comment by raunak-dev-edu** [comment]
Hello, @pavish! Could you please explain how to see if the tables are confirmed or not? What exactly do you mean by the unconfirmed table? I didn't get it.

**Comment by kgodey** [comment]
@raunak-dev-edu "Unconfirmed" tables have `import_verified` set to False in the API/backend.

**Comment by DankMemes4President** [comment]
Hey guys! Is there a documented way for me to create users with specific roles like viewer, manager and editor right now? I am able to reproduce the issue with the import_verified boolean and I would like to test it with different user roles but I am not able to find a built-in functionality to do it, do I need to manually add rows to mathesar_databaserole and mathesar_schemarole?

**Comment by Anish9901** [comment]
@DankMemes4President You can create new users using http://localhost:8000/administration/users/ and you can assign schema_roles and database_roles to appropriate users using http://localhost:8000/api/ui/v0/schema_roles/ and http://localhost:8000/api/ui/v0/database_roles/

**Comment by Hatilar420** [comment]
Hi guys, can i be assigned to this bug ?

**Comment by Anish9901** [comment]
Assigned to you @DankMemes4President , Thanks. @Hatilar420 you are already working on 6 issues at the moment, I would suggest to hold on to getting any new issues assigned until you get reviews for the respective PRs.

**Comment by DankMemes4President** [comment]
@Anish9901 I have made a couple of commits which have fixed this bug. I decided to used a confirmed_table_roles tuple much like the allowed_roles tuple. I then confirmed that my changes work fine with Admin and Manager users and Admin and Editor/Viewer users. But whenever I try to create and manually test all three of them together, i.e, Admin, Manager, Editor/Viewer users I keep getting a 'MultipleObjectsReturned' error.
This happens on the following 3 endpoints:
```
Request Method: GET
Request URL: http://127.0.0.1:8000/mathesar_tables/6/

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/mathesar/views.py", line 192, in schema_home
    schema = get_current_schema(request, schema_id, database)
  File "/code/mathesar/views.py", line 140, in get_current_schema
    return get_object_or_404(permitted_schemas, id=schema_id)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /mathesar_tables/6/
Exception Value: get() returned more than one Schema -- it returned 3!
```

```
Request Method: GET
Request URL: http://127.0.0.1:8000/api/db/v0/schemas/6/

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /api/db/v0/schemas/6/
Exception Value: get() returned more than one Schema -- it returned 3!
```
```
Request Method: GET
Request URL: http://127.0.0.1:8000/api/db/v0/tables/5/

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /api/db/v0/tables/5/
Exception Value: get() returned more than one Table -- it returned 2!
```

Apart from this issue endpoints like /api/db/v0/tables/ and /api/db/v0/schemas/ duplicate items in their response which is something that does not happen when either of Manager or Editor/Viewer user exists.

I made a git pull, and removed all my changes and yet the issues seem to persist. Can you confirm if this is an issue that actually exists or if I have misconfigured something? Also After making these changes I only need to run the Tests and make sure *all* of them pass right?

**Comment by Anish9901** [comment]
@DankMemes4President I am not sure I understand the issue you are facing can you create a draft PR with the current changes? Also please note that this is an high priority issue and is needed to be taken care of urgently. So please feel free to look through another issue to work on if you are unable to work on this.

**Comment by DankMemes4President** [comment]
Alright, I've made a draft PR with my proposed fixes
