### ISSUE TITLE
Joinable tables endpoint, table get endpoint, and query run endpoints throw 500 when requested by a user with viewer access to schema

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2518]
## Description
* Create a user with viewer access to a schema.
* Make a request to any of the following endpoints:
  - `/api/db/v0/tables/<table_id>/`
  - `/api/db/v0/tables/<table_id>/joinable_tables/`
  - `/api/db/v0/queries/run/`
* Notice a 500.
* * Note: This happens only for a user with viewer access. For editor and manager access level users, we get a 200.

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/api/db/v0/tables/249/joinable_tables/

Django Version: 3.1.14
Python Version: 3.9.16
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/db/viewsets/tables.py", line 85, in joinable_tables
    table = self.get_object()
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(

Exception Type: MultipleObjectsReturned at /api/db/v0/tables/249/joinable_tables/
Exception Value: get() returned more than one Table -- it returned 2!

```

**Comment by pavish** [comment]
@kgodey I'd like to move this issue into 'Launch blockers', since currently, users with viewer access cannot:
- Create an exploration since they can't view the joinable tables list
- Cannot view links from table inspector

**Comment by kgodey** [comment]
@pavish Yes, this sounds like a launch blocker.

**Comment by pavish** [comment]
@kgodey Thanks, moved this to launch blockers

**Comment by pavish** [comment]
Okay, I reset my db and started my dev environment from scratch and I'm no longer encountering this issue.

@kgodey I'm going to close this. I'll reopen if I encounter it again.
