### ISSUE TITLE
Records endpoint fails with 500 KeyError with this imported table

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2634]
Reported by HN user nickreese here: https://news.ycombinator.com/item?id=35008848

* Download one of the zip files from https://data.cms.gov/provider-data/archived-data/nursing-homes
  * I tested with [this zip file: nursing_homes_including_rehab_services_03_2023](https://data.cms.gov/provider-data/sites/default/files/archive/Nursing%20homes%20including%20rehab%20services/2023/nursing_homes_including_rehab_services_03_2023.zip).
* Import one of the csv files from the downloaded zip file.
  * I tested with `FY_2023_SNF_VBP_Facility_Performance.csv`.
* Notice that the Import stages, i.e. upload and preview succeed, and the final table is created.
* When the table is accessed, requests to `/api/db/v0/tables/<table_id>/records` fail with the following error:
  ```
    Environment:


    Request Method: GET
    Request URL: http://localhost:8000/api/db/v0/tables/1/records/?limit=500&offset=0

    Django Version: 3.1.14
    Python Version: 3.9.16
    Installed Applications:
    ['django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'django_property_filter',
    'mathesar']
    Installed Middleware:
    ['django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mathesar.middleware.CursorClosedHandlerMiddleware',
    'mathesar.middleware.PasswordChangeNeededMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'django_request_cache.middleware.RequestCacheMiddleware']



    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
        response = get_response(request)
      File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
        response = exception_handler(exc, context)
      File "/code/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
        raise exc
      File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
        response = handler(request, *args, **kwargs)
      File "/code/mathesar/api/db/viewsets/records.py", line 116, in list
        return paginator.get_paginated_response(serializer.data)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
        ret = super().data
      File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
        self._data = self.to_representation(self.instance)
      File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
        return [
      File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
        self.child.to_representation(item) for item in iterable
      File "/code/mathesar/api/serializers/records.py", line 90, in to_representation
        records = {columns_map[column_name]: column_value for column_name, column_value in records.items()}
      File "/code/mathesar/api/serializers/records.py", line 90, in <dictcomp>
        records = {columns_map[column_name]: column_value for column_name, column_value in records.items()}
      File "/usr/local/lib/python3.9/site-packages/bidict/_base.py", line 387, in __getitem__
        return self._fwdm[key]

    Exception Type: KeyError at /api/db/v0/tables/1/records/
    Exception Value: 'Baseline Period: FY 2019 Risk-Standardized Readmission Ra_1'

  ```

**Comment by dmos62** [comment]
The culprit seems to be truncation of column names. Not yet sure where it's happening.

`'Baseline Period: FY 2019 Risk-Standardized Readmission Ra_1'` seen in the exception should end with `Readmission Rate`, not `Ra_1`.

**Comment by dmos62** [comment]
Related to Postgres' limit of 63 bytes for identifiers: https://www.postgresql.org/docs/current/limits.html

63 bytes should correspond to 63 ASCII characters.

**Comment by dmos62** [comment]
Basically, we currently don't support column names bigger than 63 bytes. If a column name is longer than that, it gets silently truncated by Postgres and our backend state becomes invalid.

To solve this, current plan is to:

- Have our service layer reject column creation and renaming (via the column endpoints) that would cause truncation;
- When importing a CSV, truncate, on the service layer, column names that are too big:
  - Find the trucated name by iteratively truncating away characters until the concatenation of what's left and the hash of what's been truncated away fits within 63 bytes.

**Comment by dmos62** [comment]
Broke off the urgent part of this issue into its own issue #2658 and submitted a PR for it.

That issue (and PR) are about providing support for long column names during CSV import. This issue is about that, but also about handling long column names when the user is creating and renaming columns in the UI or API (which is less urgent).
