### ISSUE TITLE
Provide documentation for running Mathesar without the bash script

### ISSUE THREAD

**Issue by ovizii** [centerofci/mathesar#2761]
## Problem
Currently, installation of Mathesar requires running of a bash script from the internet which is highly insecure and requires in-depth bash knowledge to inspect the script before running it.

## Proposed solution
Provide documentation to run Mathesar via docker or via docker-compose.yml in conjunction with environmental variables.

## Additional context
See my question here: https://www.reddit.com/r/selfhosted/comments/11n2fxx/comment/jbomlgl/ 
See me being asked to open an issue here: 
https://github.com/centerofci/mathesar/issues/2034#issuecomment-1486932641 

## Suggested solution: 
https://github.com/centerofci/mathesar/issues/2741#issuecomment-1482598608

**Comment by silentninja** [comment]
Thanks for opening an issue @ovizii. @pavish @ghislaineguerin There is also a similar request on [reddit](https://www.reddit.com/r/selfhosted/comments/11n2fxx/comment/jbn9a2u/?utm_source=share&utm_medium=web2x&context=3), adding it here for reference.

**Comment by ovizii** [comment]
Btw. following this link's instructions: https://github.com/centerofci/mathesar/issues/2741#issuecomment-1482598608 isn't really working for me, I get these errors so I am very much looking forward to proper instructions :-)

See the last two lines for the actual error.
```
mathesar-db       | PostgreSQL Database directory appears to contain a database; Skipping initialization                                                                                                                                                                                                             
mathesar-db       |                                                                                                                                                                                                                                                                                                  
mathesar-db       | 2023-03-29 14:32:54.515 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by                                                                                                                                                                   
gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit                                                                                                                                                                                                                                                                        
mathesar-service  | Traceback (most recent call last):                                                                                                                                                                                                                                                               
mathesar-service  |   File "/code/install.py", line 46, in <module>                                                                                                                                                                                                                                                  
mathesar-service  |     main()                                                                                                                                                                                                                                                                                       
mathesar-service  |   File "/code/install.py", line 22, in main                                                                                                                                                                                                                                                      
mathesar-service  |     django.setup()                                                                                                                                                                                                                                                                               
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup                                                                                                                                                                                                            
mathesar-service  |     apps.populate(settings.INSTALLED_APPS)                                                                                                                                                                                                                                                       
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate                                                                                                                                                                                                   
mathesar-service  |     app_config.import_models()                                                                                                                                                                                                                                                                   
mathesar-db       | 2023-03-29 14:32:54.515 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432                                                                                                                                                                                                             
mathesar-db       | 2023-03-29 14:32:54.515 UTC [1] LOG:  listening on IPv6 address "::", port 5432                                                                                                                                                                                                                  
mathesar-db       | 2023-03-29 14:32:54.530 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                                                                                                                                                                               
mathesar-db       | 2023-03-29 14:32:54.554 UTC [27] LOG:  database system was shut down at 2023-03-29 14:27:34 UTC                                                                                                                                                                                                  
mathesar-db       | 2023-03-29 14:32:54.569 UTC [1] LOG:  database system is ready to accept connections                                                                                                                                                                                                             
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models                                                                                                                                                                                                
mathesar-service  |     self.models_module = import_module(models_module_name)                                                                                                                                                                                                                                       
mathesar-service  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                                                                                                                                                              
mathesar-service  |     return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                                                                                                  
mathesar-service  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                                                                                                                                                                                                
mathesar-service  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                                                                                             
mathesar-service  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                                                                                                                                                                                                                     
mathesar-service  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked                                                                                                                                                                                                                              
mathesar-service  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module                                                                                                                                                                                                                        
mathesar-service  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                                                                                                                                                                   
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 2, in <module>                                                                                                                                                                                               
mathesar-service  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager                                                                                                                                                                                                                  
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>                                                                                                                                                                                           
mathesar-service  |     class AbstractBaseUser(models.Model):                                                                                                                                                                                                                                                        
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__                                                                                                                                                                                                   
mathesar-service  |     new_class.add_to_class('_meta', Options(meta, app_label))                                                                                                                                                                                                                                    
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class                                                                                                                                                                                              
mathesar-service  |     value.contribute_to_class(cls, name)                                                                                                                                                                                                                                                         
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 206, in contribute_to_class                                                                                                                                                                                    
mathesar-service  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())                                                                                                                                                                                                               
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/__init__.py", line 28, in __getattr__                                   o Bracket    M-Q Previous      ^B Back           ^◀ Prev Word      ^A Home           ^P Prev Line      M-▲ Scroll Up     ^▲ Prev Block     M-( Begin of Paragr. 
mathesar-service  |     return getattr(connections[DEFAULT_DB_ALIAS], item)                                                                          ere Was      M-W Next          ^F Forward        ^▶ Next Word      ^E End            ^N Next Line      M-▼ Scroll Down   ^▼ Next Block     M-) End of Paragraph 
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 211, in __getitem__                                     
mathesar-service  |     self.ensure_defaults(alias)                                                                                                
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 172, in ensure_defaults                               
mathesar-service  |     conn = self.databases[alias]                                                                                               
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__                                
mathesar-service  |     res = instance.__dict__[self.name] = self.func(instance)                                                                   
mathesar-service  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 161, in databases                                     
mathesar-service  |     raise ImproperlyConfigured("You must define a '%s' database." % DEFAULT_DB_ALIAS)                                          
mathesar-service  | django.core.exceptions.ImproperlyConfigured: You must define a 'default' database.                   
```

**Comment by kgodey** [comment]
Thanks for reporting the error @ovizii, it's helpful. We will be working on the proper documentation very soon!

**Comment by silentninja** [comment]
@ovizii The upcoming release v0.1.2 scheduled for next week will include the updated documentation. However, you can currently access the updated documentation in the develop branch through this link: https://github.com/centerofci/mathesar/blob/develop/docs/docs/install/docker-compose/index.md#manual-install-manual.
