### ISSUE TITLE
AttributeError if there's no schemas synced to the database

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#437]
## Description

If there's no schemas synced to the database, attempting to load the schemas, tables, or databases API fails with this error:

```
Environment:


Request Method: GET
Request URL: http://staging.mathesar.org/api/v0/tables/

Django Version: 3.1.7
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1167, in __getattr__
    return self._index[key]

The above exception ('oid') was the direct cause of the following exception:
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/staging.mathesar.org/mathesar/mathesar/views/api.py", line 73, in get_queryset
    reflect_db_objects()
  File "/var/www/staging.mathesar.org/mathesar/mathesar/views/api.py", line 43, in reflect_db_objects
    reflect_schemas_from_database(database_key)
  File "/var/www/staging.mathesar.org/mathesar/mathesar/utils/schemas.py", line 34, in reflect_schemas_from_database
    schema["oid"] for schema in get_mathesar_schemas_with_oids(engine)
  File "/var/www/staging.mathesar.org/mathesar/db/schemas.py", line 57, in get_mathesar_schemas_with_oids
    select(pg_namespace.c.nspname.label('schema'), pg_namespace.c.oid)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1169, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/var/tmp/virtualenvs/staging-mathesar/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception

Exception Type: AttributeError at /api/v0/tables/
Exception Value: oid
```

## Expected behavior

The APIs should load and show an empty list if it's empty.

## To Reproduce

At this moment, you can go to (not publicly accessible):
https://staging.mathesar.org/api/v0/schemas/
https://staging.mathesar.org/api/v0/tables/
https://staging.mathesar.org/api/v0/databases/

**Comment by eito-fis** [comment]
Sorry, not sure I fully understand this issue - does no schemas synced to the database mean there is on `public` schema? Should I be able to reproduce this locally?

**Comment by kgodey** [comment]
@eito-fis yes, there's no `public` schema in the Django DB (because #365 is not fixed/merged yet). I have not tried reproducing it locally.

The issue is in this line:
```
  File "/var/www/staging.mathesar.org/mathesar/mathesar/utils/schemas.py", line 34, in reflect_schemas_from_database
    schema["oid"] for schema in get_mathesar_schemas_with_oids(engine)
```

We should not be assuming there's a schema with an `oid` key, we should first check that `get_mathesar_schemas_with_oids(engine)` returns something and then check for the `oid` key in the result if there is a result.

**Comment by eito-fis** [comment]
@kgodey I think this might actually be a version error? The detailed traceback shows the error occurs at:
```
select(pg_namespace.c.nspname.label('schema'), pg_namespace.c.oid)
```
when we try to get the `oid` column from the `pg_namespace` table. It also shows `pg_namespaces` is:
```
Table(
   'pg_namespace',
   MetaData(),
   Column('nspname', String(), table=<pg_namespace>, nullable=False),
   Column('nspowner', OID(), table=<pg_namespace>, nullable=False),
   Column('nspacl', NullType(), table=<pg_namespace>),
   schema=None
)
```

The postgres documentation shows that the `oid` column [didn't exist until v9.3](https://www.postgresql.org/docs/9.2/catalog-pg-namespace.html), and the earlier column names match up with the columns in the debug log, so it seems like we might not be on the right postgres version on the staging server?

I'm not familiar with Ansible so I'm not too sure how to proceed from here, however.

**Comment by kgodey** [comment]
Tagging in @andyharley-cci to help.

**Comment by andyharley-cci** [comment]
@eito-fis we're running `postgresql 11.12`. This appears to be the default for the version of debian. I can install a different version if required, but I think this should be correct. I'll message you directly to help with some troubleshooting.

**Comment by mathemancer** [comment]
@andyharley-cci The current version of PostgreSQL is 13.x .  This is what we were using in the docker images, and what a number of assumptions are based on.  Is it possible to use that version?

**Comment by eito-fis** [comment]
I got setup on the staging server (thanks @andyharley-cci) and can confirm the issue is caused by the postgres version. [v11 has OID as a hidden attribute](https://www.postgresql.org/docs/11/catalog-pg-namespace.html), which seems to causes sqlalchemy to not pick up the column. I'm not sure what resolution would look like here - maybe I should until we decide on what versions to support?

**Comment by kgodey** [comment]
For now, I think it makes sense to upgrade the version used on the staging server to 13. I'll reassign to @andyharley-cci to make that change.

**Comment by andyharley-cci** [comment]
Ahh that makes sense - thanks for investigating @eito-fis !

I'll upgrade the postgres version. Is this something I should document in the mathesar wiki around supported db versions?
