### ISSUE TITLE
Table OID is not unique validation error, when creating a table using a data_file

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#595]
## Description
When importing a file, we create a new table without explicitly specifying the name.
Endpoint: `http://localhost:8000/api/v0/tables/`
Request body:
```
{"schema":1,"data_files":[13]}
```

This intermittently results in a 500, with the following error:

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/v0/tables/

Django Version: 3.1.7
Python Version: 3.9.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Table matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/views/api.py", line 113, in create
    table = create_table_from_datafile(
  File "/code/mathesar/utils/tables.py", line 60, in create_table_from_datafile
    table = create_table_from_csv(data_file, name, schema)
  File "/code/mathesar/imports/csv.py", line 120, in create_table_from_csv
    table, _ = Table.objects.get_or_create(oid=db_table_oid, schema=schema, import_verified=False)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/code/mathesar/models.py", line 146, in save
    self.validate_unique()
  File "/code/mathesar/models.py", line 141, in validate_unique
    raise ValidationError("Table OID is not unique")

Exception Type: ValidationError at /api/v0/tables/
Exception Value: ['Table OID is not unique']
```

## To Reproduce
This error is intermittent, and occurs while uploading a new file from the frontend, and clicking the Next button.

I assume this has something to do with reflecting table information from connected db to our tables, while we already have the table information stored.

Related issues: https://github.com/centerofci/mathesar/issues/559, https://github.com/centerofci/mathesar/issues/577

**Comment by kgodey** [comment]
I'm assuming the culprit is this line: 

`table, _ = Table.objects.get_or_create(oid=db_table_oid, schema=schema, import_verified=False)`

Using `objects` re-reflects the table from the database, which will result in a race condition for creating this table. We should use `Table.current_objects` instead, which won't trigger reflection.

@pavish when this error happens, does the created table end up having `import_verified` be `null` instead of `False`? That would confirm my theory.

**Comment by pavish** [comment]
@kgodey Yes, the `import_verified` is `null`, when this happens.
