### ISSUE TITLE
Permissions Issues Within Docker Containers

### ISSUE THREAD

**Issue by eito-fis** [centerofci/mathesar#626]
## Description
Weird permissions errors are cropping up within containers. The UI fails to startup entirely, and the most of the API level tests are broken. Some relevant snippets

Pre-install:
```
service_1  | > mathesar_ui@0.0.0 preinstall /home/mathesar/code/mathesar_ui
service_1  | > npx npm-force-resolutions
service_1  | 
service_1  | npx: installed 6 in 1.513s
service_1  | Error: EACCES: permission denied, open './package-lock.json'
service_1  |     at Object.openSync (fs.js:498:3)
service_1  |     at Object.fs [as writeFileSync] (fs.js:1524:35)
service_1  |     at npm_force_resolutions$core$node_spit (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:19:21)
service_1  |     at switch__2144__auto__ (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:167:3)
service_1  |     at /home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:167:3
service_1  |     at npm_force_resolutions$core$state_machine__2145__auto____1 (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:818:4)
service_1  |     at cljs.core.async.impl.ioc-helpers/FN-IDX (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:834:66)
service_1  |     at cljs.core.async.impl.ioc-helpers/run-state-machine (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
service_1  |     at cljs.core.async.impl.ioc-helpers/run-state-machine-wrapped (/home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
service_1  |     at /home/mathesar/.npm/_npx/30/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:48:39
service_1  | npm ERR! code ELIFECYCLE
service_1  | npm ERR! errno 1
service_1  | npm ERR! mathesar_ui@0.0.0 preinstall: `npx npm-force-resolutions`
service_1  | npm ERR! Exit status 1
```

Vite build:
```
service_1  | vite v2.3.8 building for production...
service_1  | transforming...
service_1  | ✓ 118 modules transformed.
service_1  | rendering chunks...
service_1  | EACCES: permission denied, mkdir '/home/mathesar/code/mathesar/static'
service_1  | error during build:
service_1  | Error: EACCES: permission denied, mkdir '/home/mathesar/code/mathesar/static'
service_1  |     at Object.mkdirSync (fs.js:1009:3)
service_1  |     at mkdirpath (/home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:19040:27)
service_1  |     at mkdirpath (/home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:19038:9)
service_1  |     at mkdirpath (/home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:19038:9)
service_1  |     at /home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:19051:9
service_1  |     at new Promise (<anonymous>)
service_1  |     at writeFile (/home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:19050:12)
service_1  |     at writeOutputFile (/home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:20880:25)
service_1  |     at /home/mathesar/code/mathesar_ui/node_modules/rollup/dist/shared/rollup.js:20804:65
service_1  |     at Array.map (<anonymous>)
service_1  | npm ERR! code ELIFECYCLE
service_1  | npm ERR! errno 1
service_1  | npm ERR! mathesar_ui@0.0.0 build: `vite build`
service_1  | npm ERR! Exit status 1
```

Running API tests:
```
        try:
>           mkdir(name, mode)
E           PermissionError: [Errno 13] Permission denied: '/home/mathesar/code/.media'

/usr/local/lib/python3.9/os.py:225: PermissionError
```

Also worth noting that I've already followed the [post install instructions](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) for running docker as a non-root user. I've also tried running:
```
docker system prune -a
docker system prune --volumes
```
then re-building without success.

Interestingly, I've also tried reverting to the branch I was working on (`time_type`), which doesn't have the last major update to the docker script (#476) merged, and found that only half the issues persist. I still get the permissions error in the pre-install script, but the vite build and API level tests run totally fine.

## Environment
 - OS: Ubuntu 20.04
 - Docker: 20.10.8
 - Docker-Compose: 1.29.2

**Comment by pavish** [comment]
@eito-fis Could you please try this branch: https://github.com/centerofci/mathesar/tree/docker_container_root_user

I assume most such issues are occurring due to poor support in docker for non-root users to use bound volumes. This branch runs both our backend and frontend as root user, within the container.

Please let us know if this works.

**Comment by eito-fis** [comment]
The new branch works, both containers are running with no issues and all tests pass now.
