### ISSUE TITLE
IndexError when deleting a column

### ISSUE THREAD

**Issue by mr-gabe49** [centerofci/mathesar#663]
## Description

An indexError occurs when deleting a column through the API. Most of the time the error occurs when deleting the first or second column of a table. Deleting the last columns in a table does not seem to produce this error. 

## Expected behavior

- A column should be deleted

## To Reproduce

1. Delete the first  or second column of a table via API. Example: api/v0/tables/1/columns/1/
2. Delete the first or second column of another table via API. Example: api/v0/tables/2/columns/0/

## Screenshots

![Screenshot (35)](https://user-images.githubusercontent.com/66047479/133317146-3e4aa024-afc2-4370-9a79-1007549edccd.png)
![Screenshot (36)](https://user-images.githubusercontent.com/66047479/133317195-0da1725a-9895-4ee3-8b18-90b83eda90c4.png)

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

**Comment by kgodey** [comment]
@mr-gabe49 Can you post the full traceback? In the error message page that you posted, next to the "Traceback" header, there's a link that says "Switch to copy and paste view". If you click that, it should give you the full traceback in an easy-to-copy format.

**Comment by mr-gabe49** [comment]
@kgodey 
```
 Environment:


Request Method: GET
Request URL: http://localhost:8000/api/v0/tables/107/columns/

Django Version: 3.1.12
Python Version: 3.9.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1158, in __getitem__
    return self._index[key]

The above exception (-1) was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mathesar/api/viewsets/columns.py", line 22, in list
    return paginator.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
  File "/code/db/columns.py", line 176, in default_value
    return get_column_default(table_oid, self.column_index, self.engine)
  File "/code/db/columns.py", line 440, in get_column_default
    column = table.columns[column_index]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/base.py", line 1161, in __getitem__
    util.raise_(IndexError(key), replace_context=err)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception

Exception Type: IndexError at /api/v0/tables/107/columns/
Exception Value: -1
```

**Comment by kgodey** [comment]
Thanks!

**Comment by mr-gabe49** [comment]
@kgode Were you able to replicate the error? I wasn't sure if it was local to my environment or not.

**Comment by mathemancer** [comment]
@mr-gabe49 I'm not able to replicate it.  Is this still occurring?  To double-check (while I attempt to replicate):  This occurs when you delete columns from different tables in sequence?

**Comment by mr-gabe49** [comment]
@mathemancer Thanks for looking into this. I'm still seeing the error, even after pulling the latest master. Yes, you are correct. If I have two tables, and I delete the first column of table 1 this is what happens to the columns of table 2: The first and second **indexes** are both 0. If I then delete either column 0 or 1 of table 2, I get an IndexError. 
<h1>Table 2: Before deleting a column in Table 1</h1>
<img src="https://user-images.githubusercontent.com/66047479/134015646-6951abce-4ae6-4909-aa81-629ff3d68d0e.png" width="375" height="375">
<h1>Table 2: After deleting a column in Table 1</h1>
<img src="https://user-images.githubusercontent.com/66047479/134016265-4bef2a6f-45ca-4b82-83d0-9bdbcc23dcfa.png" width="375" height="375">

My knowledge of Django is very limited. I'm going to learn more about it to make sure this error is not just local to my machine.

**Comment by mathemancer** [comment]
@mr-gabe49 I've managed to replicate the problem.  I actually had state in _my_ local setup that kept the bug from happening.
