### ISSUE TITLE
Columns API is failing on staging

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#687]
## Problem

Table CSV uploads are failing at the import step. Upon inspection, the following API call is failing.

## Traceback

```
Environment:


Request Method: GET
Request URL: https://staging.mathesar.org/api/v0/tables/10/columns/

Django Version: 3.1.12
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/staging.mathesar.org/mathesar/mathesar/api/viewsets/columns.py", line 22, in list
    return paginator.get_paginated_response(serializer.data)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/opt/virtualenvs/staging-mathesar/lib/python3.7/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
  File "/var/www/staging.mathesar.org/mathesar/db/columns/base.py", line 103, in valid_target_types
    get_full_cast_map(self.engine).get(db_type, [])
  File "/var/www/staging.mathesar.org/mathesar/db/types/operations/cast.py", line 188, in get_full_cast_map
    return {
  File "/var/www/staging.mathesar.org/mathesar/db/types/operations/cast.py", line 98, in get_robust_supported_alter_column_type_map
    results of a Mathesar cast_to_<type> function on that column, where

Exception Type: TypeError at /api/v0/tables/10/columns/
Exception Value: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by mathemancer** [comment]
The `|` operator for merging dictionaries was added  in python 3.9.0 (the current stable releases are 3.9.x) as per [PEP 584](https://www.python.org/dev/peps/pep-0584/).  I suspect the python version on the staging server is out of date.

**Comment by kgodey** [comment]
It looks like Python 3.9 is the default on the newest Debian stable (`bullseye`), so I'm going to redeploy staging on a new server with an updated OS.

**Comment by kgodey** [comment]
I redeployed staging on a new server running Debian 11 (Bullseye), which is the new `stable`. It comes with Postgres 13 and Python 3.9, so no additional PPAs were necessary. This bug is fixed.
